[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
upload_protocol = stk500v1
upload_port = COM9
upload_speed = 19200
upload_flags =
  -P$UPLOAD_PORT
  -e
lib_deps =
  gin66/FastAccelStepper
lib_ldf_mode = chain+
; USE_LCD を有効にするには下の行のコメントを外す
build_flags = -DUSE_LCD
