[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
upload_protocol = stk500v1
upload_port = COM9
upload_speed = 19200
upload_flags =
  -P$UPLOAD_PORT
  -e
lib_deps = gin66/FastAccelStepper
